// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// v7 removed datasource.directUrl - the CLI (migrate/db push) only takes one
// `url`. Neon's pooled connection doesn't support the session behavior the
// schema engine needs, so the CLI must use the direct (unpooled) URL here.
// The app's runtime Prisma Client uses the pooled URL instead - see src/lib/prisma.ts.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DIRECT_URL"),
  },
});
